### ISSUE TITLE
Text changes

### ISSUE THREAD

**Issue by AlekseiBalyshev** [mattmas/Metamorphosis#11]
Hello, the app is something new and very useful.
Is there the technical capability to catch the changes in the text notes on the views?

**Comment by mattmas** [comment]
Aleksei - good catch. I had thought that we would have caught that, because Text is one of the parameters of a TextNote - but it turns out we're only capturing the "visible" parameters that appear in the Properties list.  I've added this as a special case, and I'll release an update shortly.

Thanks,
Matt

**Comment by mattmas** [comment]
I've published an update to the installer, version 1.0.6, that includes this.
